services:
  db:
    image: mysql:8.0
    container_name: dashboard-mysql
    restart: always
    environment:
      MYSQL_DATABASE: dashboard
      MYSQL_USER: dashboard
      MYSQL_PASSWORD: dashboard123
      MYSQL_ROOT_PASSWORD: root123
    ports:
      - "3309:3306" # Changed to avoid conflict
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - dashboard-net

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: dashboard-backend
    restart: always
    environment:
      DB_HOST: db
      DB_DATABASE: dashboard
      DB_USERNAME: dashboard
      DB_PASSWORD: dashboard123
      APP_ENV: local
      APP_KEY: base64:dummykey
      APP_DEBUG: "true"
      APP_URL: http://localhost:8000
    ports:
      - "8001:8001" # Changed to avoid conflict
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - db
    networks:
      - dashboard-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: dashboard-frontend
    ports:
      - "9001:9001" # Changed to avoid conflict
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - dashboard-net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: dashboard-phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: dashboard
      PMA_PASSWORD: dashboard123
      UPLOAD_LIMIT: 128M
    ports:
      - "8081:80"
    depends_on:
      - db
    networks:
      - dashboard-net

volumes:
  db_data:

networks:
  dashboard-net:
    driver: bridge
